require('dotenv').config();
const assert = require('node:assert/strict');
const { execFileSync } = require('node:child_process');
const schema = `stocksense_test_${Date.now()}`;
const url = new URL(process.env.DATABASE_URL); url.searchParams.set('schema', schema); process.env.DATABASE_URL = url.toString();
const directUrl = new URL(process.env.DIRECT_URL || process.env.DATABASE_URL); directUrl.searchParams.set('schema', schema); process.env.DIRECT_URL = directUrl.toString();
process.env.NODE_ENV = 'test';
process.env.AUTH_PROVIDER = 'local';
const prisma = require('../src/config/database').$raw;
let server, socketServer, liveSocket, checks = 0;
const check = (value, label) => { assert.ok(value, label); checks++; console.log(`PASS ${label}`); };
async function run() {
  execFileSync(process.execPath, [require.resolve('prisma/build/index.js'), 'migrate', 'deploy'], { env: process.env, stdio: 'pipe' });
  execFileSync(process.execPath, ['prisma/seed-demo.js'], { env: process.env, stdio: 'pipe' });
  const app = require('../src/app');
  server = app.listen(0); await new Promise(r => server.once('listening', r));
  socketServer = require('../src/services/socketService').initSocket(server);
  const base = `http://127.0.0.1:${server.address().port}/api`;
  const call = async (path, method = 'GET', body, token, cookie) => {
    if (body && ['/auth/login','/auth/reset-password','/auth/forgot-password'].includes(path)) body = {company_code:'SHELFY',...body};
    const response = await fetch(base + path, { method, headers: { 'Content-Type': 'application/json', ...(token && { Authorization: `Bearer ${token}` }), ...(cookie && { Cookie: cookie }) }, ...(body && { body: JSON.stringify(body) }) });
    return { status: response.status, body: await response.json(), cookie: response.headers.get('set-cookie')?.split(';')[0] };
  };
  let r = await call('/auth/login', 'POST', { login_id: 'manager', password: 'wrong' }); check(r.status === 401 && r.body.message === 'Invalid company, Login Id or Password', 'generic invalid credentials');
  r = await call('/auth/signup', 'POST', { login_id: 'short', email: 'valid@example.com', password: 'Password@1', confirm_password: 'Password@1' }); check(r.status === 400, 'server validates Login Id length');
  r = await call('/auth/signup', 'POST', { login_id: 'tester01', email: 'test@example.com', password: 'password', confirm_password: 'password' }); check(r.status === 400, 'server validates password strength');
  r = await call('/auth/signup', 'POST', { login_id: 'tester01', email: 'test@example.com', password: 'Password@1', confirm_password: 'Wrong@123' }); check(r.status === 400, 'server validates password confirmation');
  const early = await call('/auth/login','POST',{login_id:'manager',password:'Manager@123'});
  const invite = await call('/company/invites','POST',{role:'staff'},early.body.accessToken);
  r = await call('/auth/signup','POST',{login_id:'tester01',email:'test@example.com',password:'Password@1',confirm_password:'Password@1',role:'manager',tenant_id:999,invite_code:invite.body.data.code});
  check(r.status===201 && r.body.user.role==='staff' && r.body.user.tenant_id===early.body.user.tenant_id,'invitation company and role override client spoofing');
  const staff=r.body.accessToken;
  const duplicateInvite = await call('/company/invites','POST',{role:'staff'},early.body.accessToken);
  r=await call('/auth/signup','POST',{login_id:'tester01',email:'other@example.com',password:'Password@1',confirm_password:'Password@1',invite_code:duplicateInvite.body.data.code});check(r.status===409,'unique Login Id within company');
  const login = await call('/auth/login', 'POST', { login_id: 'manager', password: 'Manager@123' }); check(login.status === 200, 'manager login');
  const token = login.body.accessToken;
  liveSocket = new WebSocket(`ws://127.0.0.1:${server.address().port}/socket.io/?EIO=4&transport=websocket`);
  const liveEvent = event => new Promise((resolve, reject) => {
    const timer = setTimeout(() => { liveSocket.removeEventListener('message', listener); reject(new Error(`Missing realtime event ${event}`)); }, 5000);
    const listener = e => { const data = String(e.data); if (event === 'connected' ? data.startsWith('40') : data.startsWith('42') && JSON.parse(data.slice(2))[0] === event) { clearTimeout(timer); liveSocket.removeEventListener('message', listener); resolve(); } };
    liveSocket.addEventListener('message', listener);
  });
  liveSocket.addEventListener('message', e => { const data = String(e.data); if (data.startsWith('0')) liveSocket.send('40' + JSON.stringify({ token })); if (data === '2') liveSocket.send('3'); });
  await liveEvent('connected'); check(true, 'authenticated Socket.io connection');
  r = await call('/products', 'POST', { name: 'Unauthorized', sku: 'NO', category_id: 1 }, staff); check(r.status === 403, 'staff cannot create catalog products');
  const warehouses = (await call('/warehouses', 'GET', null, token)).body.data;
  const locations = (await call('/locations', 'GET', null, token)).body.data;
  const warehouse = warehouses.find(w => w.short_code === 'WH'); const location = locations.find(l => l.warehouse_id === warehouse.id);
  const category = await prisma.category.findFirst();
  r = await call('/products', 'POST', { name: 'Integration product', sku: 'TEST-001', category_id: category.id, per_unit_cost: 12.5, quantity: 5, location_id: location.id }, token);
  check(r.status === 201, 'create product with initial stock'); const product = r.body.data;
  const balance = async () => (await prisma.stockLedger.aggregate({ where: { product_id: product.id, location_id: location.id }, _sum: { quantity_delta: true } }))._sum.quantity_delta;
  check(await balance() === 5, 'initial stock recorded in ledger');
  const createDoc = async (incoming, quantity, items) => (await call(`/${incoming ? 'receipts' : 'deliveries'}`, 'POST', { warehouse_id: warehouse.id, [incoming ? 'supplier_name' : 'customer_ref']: 'Test Contact', schedule_date: '2020-01-01', items: items || [{ product_id: product.id, location_id: location.id, [incoming ? 'quantity_expected' : 'quantity']: quantity }] }, token));
  r = await createDoc(true, 10); check(r.status === 201 && /^WH\/IN\/\d{4,}$/.test(r.body.data.reference), 'warehouse receipt reference'); const receipt = r.body.data;
  r = await call(`/receipts/${receipt.id}/validate`, 'POST', {}, token); check(r.status === 409 && await balance() === 5, 'draft receipt cannot validate');
  r = await call(`/receipts/${receipt.id}/advance`, 'POST', {}, token); check(r.body.data.status === 'ready', 'receipt To Do marks Ready');
  r = await call(`/receipts/${receipt.id}`, 'PUT', { supplier_name: 'Changed' }, token); check(r.status === 409, 'ready receipt is not editable');
  const receiptEvent = liveEvent('receipt:validated');
  const concurrent = await Promise.all([1, 2].map(() => call(`/receipts/${receipt.id}/validate`, 'POST', {}, token)));
  await receiptEvent; check(true, 'receipt validation broadcasts live update');
  check(concurrent.filter(r => r.status === 200).length === 1 && await balance() === 15, 'concurrent receipt validation writes exactly once');
  check(await prisma.stockLedger.count({ where: { movement_type: 'receipt', reference_id: receipt.id } }) === 1, 'one receipt movement per line');
  r = await call(`/receipts/${receipt.id}/cancel`, 'POST', {}, token); check(r.status === 409, 'validated document cannot cancel');
  const dup = [{ product_id: product.id, location_id: location.id, quantity: 9 }, { product_id: product.id, location_id: location.id, quantity: 9 }];
  const delivery = (await createDoc(false, 18, dup)).body.data;
  r = await call(`/deliveries/${delivery.id}/advance`, 'POST', {}, token); check(r.body.data.status === 'waiting' && r.body.insufficientItems[0].requested === 18, 'duplicate delivery lines aggregate before stock check');
  r = await call(`/deliveries/${delivery.id}/validate`, 'POST', {}, token); check(r.status === 409 && await balance() === 15, 'short delivery remains Waiting without ledger writes');
  let listed = (await call('/products', 'GET', null, token)).body.data.find(p => p.id === product.id); check(listed.on_hand === 15 && listed.free_to_use === -3, 'Free to Use subtracts pending deliveries');
  r = await call(`/products/${product.id}/stock-update`, 'POST', { location_id: location.id, counted_quantity: 25 }, token); check(r.status === 201 && await balance() === 25 && r.body.data.delta === 10, 'stock-set writes adjustment delta');
  check((await prisma.deliveryOrder.findUnique({ where: { id: delivery.id } })).status === 'ready', 'restocking automatically marks eligible waiting delivery Ready');
  r = await call(`/deliveries/${delivery.id}/validate`, 'POST', {}, token); check(r.status === 200 && await balance() === 7, 'delivery validation deducts every line');
  r = await call('/move-history?search=Test%20Contact', 'GET', null, token); check(r.body.data.filter(m => m.reference === delivery.reference).length === 2, 'move history retains one row per delivery line');
  check(r.body.data.filter(m => m.reference === delivery.reference).every(m => m.direction === 'out' && m.status === 'done'), 'history direction and status');
  const canceled = (await createDoc(true, 3)).body.data;
  await call(`/receipts/${canceled.id}/cancel`, 'POST', {}, token);
  r = await call(`/receipts/${canceled.id}/advance`, 'POST', {}, token); check(r.status === 409 && await balance() === 7, 'canceled draft cannot reopen or alter stock');
  r = await createDoc(true, -1); check(r.status === 400, 'negative receipt quantity rejected');
  r = await call('/dashboard/stats', 'GET', null, token); check(r.status === 200 && r.body.data.receipts.count >= 1, 'live dashboard counts');
  let immutable = false; try { await prisma.stockLedger.updateMany({ where: { product_id: product.id }, data: { quantity_delta: 0 } }); } catch { immutable = true; }
  check(immutable && await balance() === 7, 'database rejects ledger mutation');
  const a = (await createDoc(false, 5)).body.data, b = (await createDoc(false, 5)).body.data;
  await Promise.all([a, b].map(d => call(`/deliveries/${d.id}/advance`, 'POST', {}, token)));
  const results = await Promise.all([a, b].map(d => call(`/deliveries/${d.id}/validate`, 'POST', {}, token)));
  check(results.filter(r => r.status === 200).length === 1 && await balance() === 2, 'concurrent outgoing documents cannot oversell');
  const beforeRefs = await Promise.all(Array.from({ length: 4 }, () => createDoc(true, 1)));
  check(new Set(beforeRefs.map(r => r.body.data.reference)).size === 4, 'concurrent reference allocation is unique');
  const targetLocation = locations.find(l => l.id !== location.id);
  r = await call('/transfers', 'POST', { from_location_id: location.id, to_location_id: targetLocation.id, items: [{ product_id: product.id, quantity: 1 }] }, token);
  check(r.status === 201, 'create transfer draft'); const transfer = r.body.data;
  r = await call(`/transfers/${transfer.id}/validate`, 'POST', {}, token);
  check(r.status === 200 && await balance() === 1, 'transfer deducts source atomically');
  const transferMoves = await prisma.stockLedger.findMany({ where: { movement_type: 'transfer', reference_id: transfer.id } });
  check(transferMoves.length === 2 && transferMoves.reduce((n, m) => n + m.quantity_delta, 0) === 0, 'transfer conserves total stock with paired ledger entries');
  r = await call(`/transfers/${transfer.id}`, 'PUT', { from_location_id: location.id, to_location_id: targetLocation.id, items: [{ product_id: product.id, quantity: 2 }] }, token);
  check(r.status === 409, 'validated transfer is immutable');
  r = await call('/warehouses', 'POST', { name: 'Test Warehouse', short_code: 'TEST', address: 'Test address' }, token);
  check(r.status === 200 && r.body.data.address === 'Test address', 'warehouse form fields persist');
  const testWarehouse = r.body.data;
  r = await call('/locations', 'POST', { name: 'Test rack', short_code: 'Rack1', warehouse_id: testWarehouse.id }, token);
  check(r.status === 200 && r.body.data.warehouse.id === testWarehouse.id, 'location links to parent warehouse');
  const testLoc = r.body.data;
  r = await call(`/locations/${testLoc.id}`, 'PUT', { name: 'Updated rack', short_code: 'Rack2', warehouse_id: testWarehouse.id }, token);
  check(r.status === 200 && r.body.data.short_code === 'Rack2', 'edit location');
  r = await call(`/locations/${testLoc.id}`, 'DELETE', null, token); check(r.status === 200, 'delete unused location');
  const emptyDraft = await call('/receipts', 'POST', { warehouse_id: testWarehouse.id }, token);
  r = await call(`/warehouses/${testWarehouse.id}`, 'DELETE', null, token); check(r.status === 400, 'warehouse with document references cannot be deleted');
  const crypto = require('node:crypto');
  const resetUser = await prisma.user.findFirst({ where: { login_id: 'tester01',tenant_id:login.body.user.tenant_id } });
  await prisma.otpCode.create({ data: { tenant_id:resetUser.tenant_id,user_id: resetUser.id, code_hash: crypto.createHash('sha256').update('123456').digest('hex'), expires_at: new Date(Date.now() + 300000) } });
  r = await call('/auth/reset-password', 'POST', { email: resetUser.email, otp: '123456', newPassword: 'weak' }); check(r.status === 400, 'reset enforces password strength');
  const otpResults = await Promise.all([1, 2].map(() => call('/auth/reset-password', 'POST', { email: resetUser.email, otp: '123456', newPassword: 'Changed@123', confirm_password: 'Changed@123' })));
  check(otpResults.filter(r => r.status === 200).length === 1, 'OTP consumption is atomic and cannot replay');
  r = await call('/products', 'GET', null, staff); check(r.status === 401, 'password reset revokes existing access tokens');
  r = await call('/auth/login', 'POST', { login_id: 'tester01', password: 'Changed@123' }); check(r.status === 200, 'login succeeds after password reset');
  await prisma.otpCode.create({ data: { tenant_id:resetUser.tenant_id,user_id: resetUser.id, code_hash: crypto.createHash('sha256').update('654321').digest('hex'), expires_at: new Date(Date.now() - 1000) } });
  r = await call('/auth/reset-password', 'POST', { email: resetUser.email, otp: '654321', newPassword: 'Changed@456', confirm_password: 'Changed@456' }); check(r.status === 400, 'expired OTP rejected');
  r = await call('/auth/refresh', 'POST', {}, null, login.cookie); check(r.status === 200, 'refresh session rotates'); const rotatedCookie = r.cookie;
  r = await call('/auth/refresh', 'POST', {}, null, login.cookie); check(r.status === 401, 'old refresh token cannot replay');
  await call('/auth/logout', 'POST', {}, null, rotatedCookie);
  r = await call('/auth/refresh', 'POST', {}, null, rotatedCookie); check(r.status === 401, 'logout revokes refresh token');
  execFileSync(process.execPath, ['prisma/seed-demo.js'], { env: process.env, stdio: 'pipe' });
  check(await balance() === 1, 'repeated seed preserves inventory');
  await isolation(call,token,login.body.user.tenant_id);
  console.log(`\n${checks} integration checks passed in isolated schema ${schema}.`);
}

async function isolation(call,token,tenant){
 const loginB=await call('/auth/login','POST',{company_code:'NOVA',login_id:'manager',password:'Manager@123'});const other=loginB.body.accessToken,tenantB=loginB.body.user.tenant_id;
 check(loginB.status===200&&tenant!==tenantB,'same login ID is allowed in different companies');
 const productsB=(await call('/products','GET',null,other)).body.data;const pB=productsB[0];
 const whB=(await call('/warehouses','GET',null,other)).body.data[0],locB=whB.locations[0];
 check((await call('/products','GET',null,token)).body.data.every(p=>p.tenant_id===tenant),'product lists and joins exclude other companies');
 for(const path of ['/products/'+pB.id,'/warehouses/'+whB.id,'/locations/'+locB.id]){const r=await call(path,'GET',null,token);check(r.status===404,'guessed foreign ID cannot be read: '+path);}
 check((await call('/products/'+pB.id,'PUT',{name:'Hijacked'},token)).status===404,'guessed product cannot be updated');
 check((await call('/products/'+pB.id,'DELETE',null,token)).status===404,'guessed product cannot be deleted');
 check((await call('/receipts','POST',{warehouse_id:whB.id},token)).status===400,'foreign warehouse cannot receive a document');
 const ownWh=(await call('/warehouses','GET',null,token)).body.data[0];
 const ownLoc=ownWh.locations[0];
 check((await call('/receipts','POST',{warehouse_id:ownWh.id,supplier_name:'Malicious',items:[{product_id:pB.id,location_id:ownLoc.id,quantity_expected:1}]},token)).status===400,'foreign product cannot be joined into a receipt');
 check((await call('/locations','POST',{name:'Bad join',short_code:'BAD',warehouse_id:whB.id},token)).status===400,'composite foreign keys prevent cross-company joins');
 check((await call('/company/users/'+loginB.body.user.id+'/role','PUT',{role:'staff'},token)).status===404,'manager cannot assign another company role');
 const audit=(await call('/audit','GET',null,token)).body.data;check(audit.length>0&&audit.every(a=>a.tenant_id===tenant),'audit entries are isolated');
 check(audit.every(a=>!JSON.stringify(a).includes('password_hash')),'audit snapshots redact credentials');
 const staffLogin=await call('/auth/login','POST',{login_id:'staff01',password:'Staff@123'}),staff=staffLogin.body.accessToken;
 for(const path of ['/audit','/company','/company/users','/company/invites'])check((await call(path,'GET',null,staff)).status===403,'staff cannot access '+path);
 check((await call('/company/invites','POST',{role:'manager'},staff)).status===403,'staff cannot create manager invitations');
 check((await call('/warehouses/'+ownWh.id,'DELETE',null,staff)).status===403,'staff cannot delete');
 check((await call('/settings','PUT',{language:'ta',theme:'dark',font_scale:130,role:'manager',tenant_id:tenantB},staff)).body.user.role==='staff','preferences cannot escalate role or switch company');
 const me=(await call('/auth/me','GET',null,staff)).body.user;check(me.language==='ta'&&me.theme==='dark'&&me.font_scale===130,'preferences persist per user');
 check((await call('/settings','PUT',{font_scale:200},staff)).status===400,'font scaling is bounded');
 check((await call('/company/users/'+(await call('/auth/me','GET',null,token)).body.user.id+'/role','PUT',{role:'staff'},token)).status===409,'last manager cannot be demoted');
 const create=await call('/auth/signup','POST',{company_name:'New test company',company_code:'TESTCO',login_id:'manager',email:'manager@stocksense.com',password:'Manager@123',confirm_password:'Manager@123',role:'staff'});
 check(create.status===201&&create.body.user.role==='manager','company founder becomes manager');
 const founderToken=create.body.accessToken;
 const initialWh=(await call('/warehouses','GET',null,founderToken)).body.data[0],initialCategory=(await call('/categories','GET',null,founderToken)).body.data[0];
 check(initialWh.short_code==='TESTCO'&&initialWh.locations.length===1&&initialCategory.name==='General','new companies have a usable starter warehouse, location and category');
 const founderProduct=await call('/products','POST',{name:'First product',sku:'FIRST',category_id:initialCategory.id,quantity:4,location_id:initialWh.locations[0].id},founderToken);
 check(founderProduct.status===201,'new company manager can create initial inventory');
 const firstReceipt=await call('/receipts','POST',{warehouse_id:initialWh.id,supplier_name:'First supplier',items:[{product_id:founderProduct.body.data.id,location_id:initialWh.locations[0].id,quantity_expected:1}]},founderToken);
 check(firstReceipt.status===201&&firstReceipt.body.data.reference==='TESTCO/IN/0001','company short code feeds its starter warehouse references');
 const invitation=await call('/company/invites','POST',{role:'staff',email:'join@example.com'},token);
 const wrong=await call('/auth/signup','POST',{login_id:'joiner01',email:'wrong@example.com',password:'Joiner@123',confirm_password:'Joiner@123',invite_code:invitation.body.data.code});check(wrong.status===400,'email restricted invitations reject another email');
 const joined=await call('/auth/signup','POST',{login_id:'joiner01',email:'join@example.com',password:'Joiner@123',confirm_password:'Joiner@123',invite_code:invitation.body.data.code});check(joined.status===201&&joined.body.user.tenant_id===tenant,'invitation joins its issuing company');
 check((await call('/auth/signup','POST',{login_id:'joiner02',email:'join@example.com',password:'Joiner@123',confirm_password:'Joiner@123',invite_code:invitation.body.data.code})).status===400,'used invitations cannot replay');
 const own=(await call('/products','GET',null,token)).body.data[0];
 const dashboardA=(await call('/dashboard/stats','GET',null,token)).body.data,dashboardB=(await call('/dashboard/stats','GET',null,other)).body.data;
 check(dashboardA.products===6&&dashboardB.products===5,'dashboard totals and cached KPIs are company scoped');
 const receiptB=await call('/receipts','POST',{warehouse_id:whB.id},other);
 check(receiptB.body.data.reference==='WH/IN/0003','reference numbering advances independently in each company');
 const actor=(await call('/auth/me','GET',null,token)).body.user;
 const codeHash=require('crypto').createHash('sha256').update('112233').digest('hex');
 const otp=await prisma.otpCode.create({data:{tenant_id:tenant,user_id:actor.id,code_hash:codeHash,expires_at:new Date(Date.now()+300000)}});
 check((await call('/auth/reset-password','POST',{company_code:'NOVA',email:actor.email,otp:'112233',newPassword:'Changed@123',confirm_password:'Changed@123'})).status===400&&(await prisma.otpCode.findUnique({where:{id:otp.id}})).used===false,'password reset codes cannot cross companies with identical emails');
 await prisma.$executeRawUnsafe("CREATE FUNCTION reject_test_audit() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.entity_type='product' AND NEW.action='product.update' THEN RAISE EXCEPTION 'Test audit failure'; END IF; RETURN NEW; END $$");
 await prisma.$executeRawUnsafe('CREATE TRIGGER reject_test_audit BEFORE INSERT ON audit_logs FOR EACH ROW EXECUTE FUNCTION reject_test_audit()');
 const rolledBack=await call('/products/'+own.id,'PUT',{name:'Must roll back'},token);
 await prisma.$executeRawUnsafe('DROP TRIGGER reject_test_audit ON audit_logs');await prisma.$executeRawUnsafe('DROP FUNCTION reject_test_audit()');
 check(rolledBack.status===500&&(await prisma.product.findUnique({where:{id:own.id}})).name===own.name,'business mutation rolls back when audit insertion fails');
 const {run}=require('../src/config/tenant'),repo=require('../src/config/database'),cache=require('../src/config/redis');
 await run({tenant_id:tenant},()=>cache.set('isolation:test','A','EX',60));await run({tenant_id:tenantB},()=>cache.set('isolation:test','B','EX',60));
 check(await run({tenant_id:tenant},()=>cache.get('isolation:test'))==='A'&&await run({tenant_id:tenantB},()=>cache.get('isolation:test'))==='B','cache keys cannot leak across companies');
 let closed=false;try{await repo.product.findMany();}catch{closed=true;}check(closed,'repository fails closed without a company context');
 check(await run({tenant_id:tenant},()=>repo.product.findUnique({where:{id:pB.id}}))===null,'repository applies company scoping to unique lookups');
 let immutable=false;try{await prisma.auditLog.update({where:{id:audit[0].id},data:{action:'tampered'}});}catch{immutable=true;}check(immutable,'audit history is immutable in the database');
 const socket= new WebSocket('ws://127.0.0.1:'+server.address().port+'/socket.io/?EIO=4&transport=websocket');let leaked=false;
 const connected=new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error('Socket B timeout')),5000);socket.addEventListener('message',e=>{const data=String(e.data);if(data.startsWith('0'))socket.send('40'+JSON.stringify({token:other}));if(data.startsWith('40')){clearTimeout(timer);resolve();}if(data==='2')socket.send('3');if(data.startsWith('42')&&JSON.parse(data.slice(2))[0]==='isolation:probe')leaked=true;});});
 await connected;await run({tenant_id:tenant},()=>require('../src/services/socketService').emitEvent('isolation:probe',{secret:'Company A'}));await new Promise(r=>setTimeout(r,150));socket.close();check(!leaked,'Socket.io excludes other company rooms');
 // Provider calls are mocked here; the verifier's trust checks have their own unit suite.
 process.env.AUTH_PROVIDER='clerk';
 const identityService=require('../src/services/clerkIdentity');
 const verifyOriginal=identityService.verifyEmailIdentity,sessionOriginal=identityService.assertSession;
 const managerAccount=await prisma.user.findFirst({where:{tenant_id:tenant,login_id:'manager'}});
 let verifiedEmail=managerAccount.email;
 identityService.verifyEmailIdentity=async bearer=>{if(bearer!=='test-clerk-token')throw Object.assign(new Error('Invalid verification'),{statusCode:401});return {userId:'user_test_clerk',sessionId:'sess_test_clerk',email:verifiedEmail};};
 identityService.assertSession=async(id,userId)=>{assert.equal(id,'sess_test_clerk');assert.equal(userId,'user_test_clerk');};
 check((await call('/auth/login','POST',{company_code:'SHELFY',login_id:'manager',password:'Manager@123'})).status===410,'Clerk mode disables password login');
 check((await call('/auth/forgot-password','POST',{email:managerAccount.email})).status===410,'Clerk mode disables custom OTP delivery');
 check((await call('/products','GET',null,token)).status===401,'Clerk mode rejects legacy access tokens');
 check((await call('/auth/clerk/session','POST',{company_code:'SHELFY'},'forged')).status===401,'Clerk exchange rejects unverified requests');
 const clerkLogin=await call('/auth/clerk/session','POST',{company_code:'SHELFY',role:'staff',tenant_id:tenantB},'test-clerk-token');
 check(clerkLogin.status===200&&clerkLogin.body.user.tenant_id===tenant&&clerkLogin.body.user.role==='manager','Clerk login preserves database company and role');
 check((await prisma.user.findUnique({where:{id:managerAccount.id}})).clerk_user_id==='user_test_clerk','verified email links existing account');
 check((await call('/products','GET',null,clerkLogin.body.accessToken)).status===200,'Clerk exchanged token accesses scoped inventory');
 check((await call('/auth/clerk/session','POST',{company_code:'UNKNOWN'},'test-clerk-token')).status===403,'Clerk cannot enter an unknown company');
 check((await call('/auth/refresh','POST',{},null,clerkLogin.cookie)).status===200,'Clerk refresh rechecks provider session');
 check((await call('/settings/password','POST',{},clerkLogin.body.accessToken)).status===409,'Clerk accounts cannot set a local password');
 const clerkInvite=await call('/company/invites','POST',{email:'newclerk@example.com',role:'staff'},clerkLogin.body.accessToken);
 verifiedEmail='wrong@example.com';
 check((await call('/auth/clerk/session','POST',{intent:'join',invite_code:clerkInvite.body.data.code,login_id:'clerk01',email:'newclerk@example.com'},'test-clerk-token')).status===400,'invitation email uses verified identity, not client email');
 verifiedEmail='newclerk@example.com';
 const duplicateClerkJoin=await call('/auth/clerk/session','POST',{intent:'join',invite_code:clerkInvite.body.data.code,login_id:'clerk01',role:'manager',tenant_id:tenantB},'test-clerk-token');
 // Use a distinct Clerk identity for this new user in the same company.
 check(duplicateClerkJoin.status===409,'one Clerk identity cannot be duplicated within a company');
 identityService.verifyEmailIdentity=async()=>({userId:'user_new_clerk',sessionId:'sess_new_clerk',email:verifiedEmail});
 const joinedNew=await call('/auth/clerk/session','POST',{intent:'join',invite_code:clerkInvite.body.data.code,login_id:'clerk01',role:'manager',tenant_id:tenantB},'test-clerk-token');
 check(joinedNew.status===201&&joinedNew.body.user.role==='staff'&&joinedNew.body.user.tenant_id===tenant&&joinedNew.body.user.theme==='light','Clerk invitation signup derives role and defaults to light');
 identityService.verifyEmailIdentity=verifyOriginal;identityService.assertSession=sessionOriginal;
}

run().catch(e => { console.error(e); process.exitCode = 1; }).finally(async () => {
  liveSocket?.close();
  if (socketServer) await new Promise(r => socketServer.close(r));
  else if (server) await new Promise(r => server.close(r));
  if (/^stocksense_test_\d+$/.test(schema)) await prisma.$executeRawUnsafe(`DROP SCHEMA IF EXISTS "${schema}" CASCADE`);
  await prisma.$disconnect();
  setTimeout(() => process.exit(process.exitCode || 0), 100);
});
